name: Linux (Clang)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux_clang:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        clangver: [ 8, 11, 12, 13 ]
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.21.x'

      - name: Set up clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.clangver }}
          platform: x64

      - uses: actions/checkout@v2

      - name: Make build folder
        working-directory: ${{github.workspace}}
        run: mkdir build

      - name: CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -- -j4

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 2

      - name: Test
        working-directory: ${{github.workspace}}/build/tests/
        run: ./pocketlzma_tests --order rand