name: Windows (MSVC)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Windows_2019:
    runs-on: windows-2019
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.21.x'

      - uses: actions/checkout@v2

      - name: Make build folder
        working-directory: ${{github.workspace}}
        run: mkdir build

      - name: CMake - Visual Studio 2019
        working-directory: ${{github.workspace}}/build
        run: cmake ../ -G "Visual Studio 16 2019"

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: tests/Debug/pocketlzma_tests.exe --order rand

  Windows_2022:
    runs-on: windows-2022
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.21.x'

      - uses: actions/checkout@v2

      - name: Make build folder
        working-directory: ${{github.workspace}}
        run: mkdir build

      - name: CMake - Visual Studio 2022
        working-directory: ${{github.workspace}}/build
        run: cmake ../ -G "Visual Studio 17 2022"

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: tests/Debug/pocketlzma_tests.exe --order rand